language: java
after_success:
- mvn clean test jacoco:report coveralls:report
before_install:
- openssl aes-256-cbc -K $encrypted_b4f0616205c0_key -iv $encrypted_b4f0616205c0_iv
  -in src/test/resources/settings.json.enc -out src/test/resources/settings.json -d
