language: java

notifications:
  email:
    - bitcodin-java@bitmovin.net

before_install:
  - openssl aes-256-cbc -K $encrypted_cdfcb749ec27_key -iv $encrypted_cdfcb749ec27_iv -in src/test/resources/settings.json.enc -out src/test/resources/settings.json -d

install: 
  - mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn clean test jacoco:report coveralls:report
